spring:
  data:
    mongodb:
      uri: mongodb+srv://admin:admin@cluster0.bkkmgbg.mongodb.net/banking
ledger:
  base-url: http://localhost:8081
logging:
  level:
    org.springframework.web.reactive.function.client.ExchangeFunctions: TRACE
Server:
    port: 8081
